DROP TABLE IF EXISTS "credenziali";
CREATE TABLE "credenziali" ("id_utente_cred" INTEGER PRIMARY KEY  NOT NULL , "password" VARCHAR NOT NULL );
INSERT INTO "credenziali" VALUES(3,'robert');
INSERT INTO "credenziali" VALUES(33,'roberto');
INSERT INTO "credenziali" VALUES(77,'luca');
INSERT INTO "credenziali" VALUES(101,'marina');
INSERT INTO "credenziali" VALUES(111,'mario');
DROP TABLE IF EXISTS "problemi";
CREATE TABLE "problemi" ("id_problema" INTEGER PRIMARY KEY  NOT NULL , "tipo_problema" VARCHAR NOT NULL, "soluzione" VARCHAR, "tipo_barca" VARCHAR, "tipologia" VARCHAR);
INSERT INTO "problemi" VALUES(1,'La barca si muove?','Controlla che la barca si muova','charter','011');
INSERT INTO "problemi" VALUES(2,'La barca vira?','Controlla il timone','charter','012');
INSERT INTO "problemi" VALUES(3,'Hai un problema allo scafo?','Controlla se ci sono problemi allo scafo','charter','013');
INSERT INTO "problemi" VALUES(4,'Stai navigando a vela?','Controlla se stai andando a vela','charter','0111');
INSERT INTO "problemi" VALUES(5,'Stai navigando a motore?','Controlla se stai andando a motore','charter','0112');
INSERT INTO "problemi" VALUES(6,'Il timone è bloccato?','Controlla che il meccanismo di blocco della ruota del timone non sia inserito, se è inserito sbloccalo tirando l''apposita leva','charter','0121');
INSERT INTO "problemi" VALUES(7,'Ci sono alghe sul timone?','Controlla che delle alghe attorcigliate non blocchino le pale del timone','charter','0122');
INSERT INTO "problemi" VALUES(8,'Hai una falla nello scafo?','Tampona la falla utilizzando il kit di riparazione','charter','0131');
INSERT INTO "problemi" VALUES(9,'E presente del fumo a bordo?','Controlla la presenza di fumo, se presente prepara un estintore ','charter','0132');
INSERT INTO "problemi" VALUES(10,'Il fumo esce dal motore?','Spegni il motore e controlla le condutture dei gas di scarico','charter','01321');
INSERT INTO "problemi" VALUES(11,'Il fumo proviene dalla cucina?','Spegni i fornelli e rimuovi materiale facilmente infiammabile','charter','01322');
INSERT INTO "problemi" VALUES(12,'Hai issato la vela?','Issa la vela tirando l''apposita drizza','charter','01111');
INSERT INTO "problemi" VALUES(13,'Il motore è acceso?','Devi accendere il motore, gira la chiave e accelera leggermente','Charter','01121');
INSERT INTO "problemi" VALUES(14,'Hai messo il carburante?','Fai rifornimento.','charter','011211');
INSERT INTO "problemi" VALUES(15,'Hai un problema allo scafo?','Controlla se ci sono problemi allo scafo',' diporto ','023');
INSERT INTO "problemi" VALUES(16,'Si solleva la deriva?','Controlla che la deriva non sia già sollevata',' diporto ','024');
INSERT INTO "problemi" VALUES(17,'La barca si muove?','Controlla che la barca si muova','diporto','021');
INSERT INTO "problemi" VALUES(18,'La barca vira?','Controlla il timone','diporto','022');
INSERT INTO "problemi" VALUES(19,'Il timone è bloccato?','Controlla che il meccanismo di blocco della ruota del timone non sia inserito, se è inserito sbloccalo tirando l''apposita leva','diporto','0221');
INSERT INTO "problemi" VALUES(20,'Ci sono alghe sul timone?','Controlla che delle alghe attorcigliate non blocchino le pale del timone','diporto','0222');
INSERT INTO "problemi" VALUES(21,'Hai una falla nello scafo?','Tampona la falla utilizzando il kit di riparazione','diporto','0231');
INSERT INTO "problemi" VALUES(22,'E presente del fumo a bordo?','Controlla la presenza di fumo, se presente prepara un estintore ','diporto','0232');
INSERT INTO "problemi" VALUES(23,'Lo scafo è pieno di incrostazioni?','Spegni il motore, ferma la barca e effettua la pulizia',' diporto ','0233');
INSERT INTO "problemi" VALUES(24,'Funziona il motore di sollevamento della deriva?','Smonta il coperchio, usa la leva manuale',' diporto ','0241');
INSERT INTO "problemi" VALUES(25,'Stai navigando a vela?','Controlla se stai andando a vela','diporto','0211');
INSERT INTO "problemi" VALUES(26,'Stai navigando a motore?','Controlla se stai andando a motore','diporto','0212');
INSERT INTO "problemi" VALUES(27,'Il fumo esce dal motore?','Spegni il motore e controlla le condutture dei gas di scarico','diporto','02321');
INSERT INTO "problemi" VALUES(28,'Il fumo proviene dalla cucina?','Spegni i fornelli e rimuovi materiale facilmente infiammabile','diporto','02322');
INSERT INTO "problemi" VALUES(29,'Hai issato la vela?','Issa la vela tirando l''apposita drizza','diporto','02111');
INSERT INTO "problemi" VALUES(30,'Il motore è acceso?','Devi accendere il motore, gira la chiave e accelera leggermente','diporto','02121');
INSERT INTO "problemi" VALUES(31,'Hai messo il carburante?','Fai rifornimento.','diporto','021211');
INSERT INTO "problemi" VALUES(32,'1','1','1','0');
INSERT INTO "problemi" VALUES(33,'2','Controlla sul libretto che tipo di barca è','charter','01');
INSERT INTO "problemi" VALUES(34,'3','Controlla sul libretto che tipo di barca è','diporto','02');
DROP TABLE IF EXISTS "utenti";
CREATE TABLE "utenti" ("id_utente" INTEGER PRIMARY KEY  NOT NULL , "nome" VARCHAR NOT NULL , "cognome" VARCHAR NOT NULL , "numerotel" VARCHAR NOT NULL , "indirizzo" VARCHAR NOT NULL );
INSERT INTO "utenti" VALUES(3,'robert','ross','333657','piazza lunga');
INSERT INTO "utenti" VALUES(33,'roberto','rossi','3513879','piazza napoli');
INSERT INTO "utenti" VALUES(77,'luca','verdi','0035413','via costa');
INSERT INTO "utenti" VALUES(101,'marina','damon','3541013','via qualcosa');
INSERT INTO "utenti" VALUES(111,'mario','rossi','0235413','via anonima');
INSERT INTO "utenti" VALUES(466,'mario','rossi','332546','viale misterioso');
INSERT INTO "utenti" VALUES(539,'giulia','ferrari','3888615','via pieve');
INSERT INTO "utenti" VALUES(1035,'anna','bianchi','35411879','via napoleone');
INSERT INTO "utenti" VALUES(1036,'anna','bianchini','0004758','via bonaparte');
INSERT INTO "utenti" VALUES(1107,'luca','neri','00535447','viale piave');
